# Generated by Django 3.1.5 on 2023-01-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221215_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time_create'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='product',
            name='prepayment',
            field=models.IntegerField(null=True, verbose_name='Предоплата'),
        ),
        migrations.AddField(
            model_name='product',
            name='residue',
            field=models.IntegerField(null=True, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(max_length=300, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(verbose_name='Цена покупки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='base.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
